config/routes.rb
Myapp::Application.routes.draw do
  scope "(:locale)", :locale => /en|ar/ do
    devise_scope :user do
      root :to => 'devise/sessions#new'
      delete "sign out" => "devise/session#destroy"
    end
    devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: '', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
    
    get 'home/index' => 'home#index'    
    get 'factory/new' => 'factory#new'
    get 'addnew' => 'home#addnew'
    post 'addnew' => 'home#addnew'
    get 'destroy' => 'home#destroy'
    get 'etsr' => 'home#etsr'
    get 'loadexisting' => 'home#loadexisting'
    post "modalclass" => 'home#modalclass'
    get "modalclass"  => 'home#modalclass'
    post "modalprop" => 'home#modalprop'
    get "modalprop"  => 'home#modalprop'
    get 'settings' => 'setting#index'
    post 'settings' => 'setting#index'
    get 'view' => 'home#view'
    post 'view' => 'home#view'
    post 'update' => 'home#update'
    get 'update' => 'home#update'
    get 'dictionary_detail' => 'home#dictionary_detail'  
    get 'ajax_property' => 'home#ajax_property'  
    get 'template_search' => 'home#template_search'
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    require 'will_paginate/array'
    before_filter :setting, :only => [:index, :view, :update, :addnew]

    def index
        @organization = current_user.Organization_ID
        if params[:search]
           @vs = params[:search]
           @madein_ksa = MaterialMaster.where("organization_ID = ? AND datedeleted = ?",@organization,'0000-00-00 00:00:00').where("legacy_description like ? OR material_id like ? OR cat_id like ? OR short_description like ? OR long_description like ?","%#{@vs}%","%#{@vs}%","%#{@vs}%","%#{@vs}%","%#{@vs}%").paginate(:page => params[:page], :per_page => 12)
           @madein_count = MaterialMaster.where("legacy_description like ? OR material_id like ? OR cat_id like ? OR short_description like ? OR long_description like ?","%#{@vs}%","%#{@vs}%","%#{@vs}%","%#{@vs}%","%#{@vs}%").where("organization_ID = ? AND datedeleted = ?",@organization,'0000-00-00 00:00:00').count
        else
            @madein_ksa = MaterialMaster.where("organization_ID = ? and datedeleted = ?",@organization,'0000-00-00 00:00:00').paginate(:page => params[:page], :per_page => 12)
            @madein_count = MaterialMaster.where("organization_ID = ? and datedeleted = ?",@organization,'0000-00-00 00:00:00').count
        end        
    end

    def modalclass
        @listall = params[:listall]
        @page = params[:page]
        @per_page=10
        @startfrom= (@page.to_i-1) * @per_page;

        if @listall=='1'
            @modal_class_count = ConceptDn.count_by_sql(["SELECT count(*) from `concept_dn` WHERE  concept_type_ID = '0161-1#CT-01#1'"])
            @modal_class = ConceptDn.find_by_sql([" SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'s' FROM  `concept_dn` a,  `corp_ignames` b WHERE a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id  AND a.term_content <>  '' UNION SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'y' FROM  `concept_dn` a WHERE a.concept_type_ID =  '0161-1#CT-01#1' AND a.term_content <>  '' AND a.concept_ID not in (SELECT DISTINCT a.concept_ID FROM  `concept_dn` a,  `corp_ignames` b WHERE  a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content <>  '') LIMIT #{@startfrom},#{@per_page} "])
           
        elsif @listall=='0' 
            @class_name = params[:class_name]
            @organization = params[:organization]
            @language = params[:language]
            @query = params[:query]
           
            if @query=="like"
                if @class_name!=''  && @organization!='' && @language!=''

                @modal_class_count = ConceptDn.count_by_sql(["SELECT count(*) from `concept_dn` where concept_type_ID = '0161-1#CT-01#1' and  language_ID = ? and term_organization_name = ? and term_content like ?","#{@language}","#{@organization}","%#{@class_name}%"])

                @modal_class = ConceptDn.find_by_sql(["SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'s' FROM  `concept_dn` a,  `corp_ignames` b WHERE a.language_ID = ?  AND a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content like ? AND a.term_content <>  '' AND a.term_organization_name = ? UNION SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'y' FROM  `concept_dn` a WHERE a.language_ID = ? AND a.concept_type_ID =  '0161-1#CT-01#1' AND a.term_content like ? AND a.term_content <>  '' AND a.term_organization_name = ? AND a.concept_ID not in (SELECT DISTINCT a.concept_ID FROM  `concept_dn` a,  `corp_ignames` b WHERE a.language_ID = ? AND a.term_content like ? AND a.term_organization_name = ? AND a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content <>  '') LIMIT #{@startfrom},#{@per_page} ","#{@language}","%#{@class_name}%","#{@organization}","#{@language}","%#{@class_name}%","#{@organization}","#{@language}","%#{@class_name}%","#{@organization}"]) 

 
                elsif @class_name!='' && @organization=='' && @language==''

                     @modal_class_count = ConceptDn.count_by_sql([" SELECT count(*) from `concept_dn` where concept_type_ID = '0161-1#CT-01#1' and   term_content like ?","%#{@class_name}%"])

                    @modal_class =  ConceptDn.find_by_sql(["SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'s' FROM  `concept_dn` a,  `corp_ignames` b WHERE a.language_ID =  ? and a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content like ? AND a.term_content <>  '' UNION SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'y' FROM  `concept_dn` a WHERE a.concept_type_ID =  '0161-1#CT-01#1' AND a.term_content like ? AND a.term_content <>  '' AND a.concept_ID not in (SELECT DISTINCT a.concept_ID FROM  `concept_dn` a,  `corp_ignames` b  WHERE a.language_ID =  ? and a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content like ? AND a.term_content <>  '') LIMIT  #{@startfrom},#{@per_page}","#{@language}","%#{@class_name}%","%#{@class_name}%","#{@language}","%#{@class_name}%"])


 
                elsif @organization!='' && @class_name=='' && @language==''

                     @modal_class_count = ConceptDn.count_by_sql([" SELECT count(*) from `concept_dn` where concept_type_ID = '0161-1#CT-01#1' and  language_ID = '0161-1#LG-000001#1'and term_organization_name = ? ","%#{@organization}%"])

                    @modal_class = ConceptDn.find_by_sql([" SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'s' FROM  `concept_dn` a,  `corp_ignames` b WHERE a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content <>  '' AND a.term_organization_name = ? UNION SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'y' FROM  `concept_dn` a WHERE a.concept_type_ID =  '0161-1#CT-01#1' AND a.term_content <>  ''  AND a.term_organization_name = ? AND a.concept_ID not in (SELECT DISTINCT a.concept_ID FROM  `concept_dn` a,  `corp_ignames` b WHERE a.language_ID = '0161-1#LG-000001#1' AND a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content <>  ''AND a.term_organization_name = ?) LIMIT #{@startfrom},#{@per_page} ","#{@organization}","#{@organization}","#{@organization}"]) 


                elsif @language!='' && @organization=='' && @class_name==''

                     @modal_class_count = ConceptDn.count_by_sql([" SELECT count(*) from `concept_dn` where concept_type_ID = '0161-1#CT-01#1' and  language_ID  = ?","#{@language}"])

                    @modal_class = ConceptDn.find_by_sql([" SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'s' FROM  `concept_dn` a,  `corp_ignames` b WHERE a.language_ID = ? AND a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content <>  ''  UNION SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'y' FROM  `concept_dn` a WHERE a.language_ID =  ? AND a.concept_type_ID =  '0161-1#CT-01#1' AND a.term_content <>  '' AND a.concept_ID not in (SELECT DISTINCT a.concept_ID FROM  `concept_dn` a,  `corp_ignames` b WHERE a.language_ID = ? AND a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content <>  '') LIMIT #{@startfrom},#{@per_page} ","#{@language}","#{@language}","#{@language}"]) 
             
                elsif @class_name!='' && @organization!='' && @language==''

                     @modal_class_count = ConceptDn.count_by_sql([" SELECT count(*) from `concept_dn` where concept_type_ID = '0161-1#CT-01#1' and  language_ID ='0161-1#LG-000001#1' and term_organization_name = ? and term_content like ?","#{@organization}","%#{@class_name}%"])

                    @modal_class = ConceptDn.find_by_sql([" SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'s' FROM  `concept_dn` a,  `corp_ignames` b WHERE a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content like ? AND a.term_content <>  '' AND a.term_organization_name = ? UNION SELECT DISTINCT a.term_content, a.concept_ID, a.term_ID, a.definition_ID, a.term_organization_name, a.definition_content, a.language_name,a.language_ID,'y' FROM  `concept_dn` a WHERE a.concept_type_ID =  '0161-1#CT-01#1' AND a.term_content like ? AND a.term_content <>  ''  AND a.term_organization_name = ? AND a.concept_ID not in (SELECT DISTINCT a.concept_ID FROM  `concept_dn` a,  `corp_ignames` b WHERE a.language_ID =  '0161-1#LG-000001#1' AND a.concept_type_ID =  '0161-1#CT-01#1' AND a.concept_id = b.Class_id AND a.term_content <>  '' AND a.term_content like ? AND a.term_organization_name = ?) LIMIT #{@startfrom},#{@per_page} ","%#{@class_name}%","#{@organization}","%#{@class_name}%","#{@organization}","%#{@class_name}%","#{@organization}"]) 


                elsif @class_name!='' && @organization=='' && @language!=''

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/ajax_property.html.erb
<div class="col-md-12">
 <table class="table table-striped table-bordered table-hover dataTables-example">
    <thead>
      <tr>
        <th class="text-center" style="background:#1AB394;color:#f3f3f4 !important;">Property</th>
        <th class="text-center" style="background:#1AB394;color:#f3f3f4 !important;">Definition</th>
      </tr>
    </thead>
    <tbody>
      <% @xml_rg.each do|x|%>
      <% @proref=x.propertyRef %>
       <tr>
        <% if x.Required== 'y' %>
            <td> <%= link_to x.property , {:controller => :home,:action => :dictionary_detail, :term => '', :esci => x.propertyRef, :def => ''}, :target => "_blank" %> <span class="text-danger" style="font-size: 16px;">  <b>*</b></span></td>
          <%else%>
          <td> <%= link_to x.property , {:controller => :home,:action => :dictionary_detail, :term => '', :esci => Base64.encode64(x.propertyRef), :def => ''}, :target => "_blank" %></td>
        <% end %>
        <td>
            <%= x.Property_Definition %>
        </td>
      <% end %>
      </tr>
    </tbody>
  </table>
</div>

<% content_for :javascript do %>

<script type="text/javascript">

$(function() {
  $('.dataTables-example').dataTable({
      "dom": 'T<"clear">lfrtip',
      "tableTools": {
          "sSwfPath": "../assets/dataTables/swf/copy_csv_xls_pdf.swf"
      }
  });
});
</script>

<% end %>

app/views/home/dictionary_detail.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <div class="clearfix"></div><br><br><br><br>
    <ol class="breadcrumb" style="background:#F3F3F4; padding:6px;">
      <li class="active">
        <%- if I18n.locale== :ar %>
          <span class="">
              <a href="<%= url_for :controller => 'home', :action => 'index' %>">الصفحة الرئيسية</a>                   
          </span>
        <% else %>
          <span class="">
           <a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a>
          </span>
        <% end -%>  
      </li>
      <li class="active">
          <%- if I18n.locale== :ar %>
          <span class="">Dictionary
              <!-- <a href="<%= url_for :controller => 'home', :action => 'index' %>">eSTS's</a> -->                   
          </span>
        <% else %>
          <span class="">Dictionary
           <!-- <a href="<%= url_for :controller => 'home', :action => 'index' %>">eSTS's</a> -->                   
          </span>
        <% end -%>
      </li>
    </ol>        
  </div>
</div>
<%= @len_sd %>

<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
  <div class="col-lg-4">
    <div class="ibox" >
      <div class="ibox-title" style="background:#1C84C6;color:#f3f3f4 !important;">
        <h5> <%- if I18n.locale== :ar %>
          <span class="">
            <% @ar_term = Language.select("language_property").where("language_id = ?  AND language_type = ? ", '24','ar')%>
            <% @ar_term.each do |ar_term|%>
            <%= ar_term.language_property %>
             <% end %>
          </span>
          <% else %>
            <span class="">
              <% @en_term = Language.select("language_property").where("language_id = ?  AND language_type = ? ", '24','en')%>
              <% @en_term.each do |en_term|%>
              <%= en_term.language_property %>
               <% end %>
            </span>
        <% end -%> </h5>
        <div class="ibox-tools">
            <a class="collapse-link" style="color:#f3f3f4 !important;">
                <i class="fa fa-chevron-up"></i>
            </a>
           
            <a class="close-link" style="color:#f3f3f4 !important;">
                <i class="fa fa-times"></i>
            </a>
        </div>
      </div>
      <div class="ibox-content" style="border:1px solid #1C84C6;">
       <table class="table table-bordered">
        <thead>
          <tr>
            <th >Concept Identifier</th>
            <th >Status</th>
          </tr>
        </thead>
        <tbody>
          <tr>                    
            <td><%= @esci%></td>                      
            <td>Active</td>                      
          </tr>
        </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-lg-12">
   <div class="ibox">
    <div class="ibox-title" style="background:#1C84C6;color:#f3f3f4 !important;">
      <h5> <%- if I18n.locale== :ar %>
        <span class="">
          <% @ar_term = Language.select("language_property").where("language_id = ?  AND language_type = ? ", '23','ar')%>
          <% @ar_term.each do |ar_term|%>
          <%= ar_term.language_property %>
           <% end %>
        </span>
      <% else %>
        <span class="">
          <% @en_term = Language.select("language_property").where("language_id = ?  AND language_type = ? ", '23','en')%>
          <% @en_term.each do |en_term|%>
          <%= en_term.language_property %>
           <% end %>
        </span>
      <% end -%> </h5>
      <div class="ibox-tools">
        <a class="collapse-link" style="color:#f3f3f4 !important;">
            <i class="fa fa-chevron-up"></i>
        </a>
       
        <a class="close-link" style="color:#f3f3f4 !important;">
            <i class="fa fa-times"></i>
        </a>
      </div>
    </div>
    <div class="ibox-content" style="border:1px solid #1C84C6;">
      <table class="table table-bordered">
        <thead> 
          <tr> 
              <th>Term ID</th>
              <th>Language</th>
              <th>Term</th>
              <th>Source</th>
              <th>Source Reference</th>
              <th>Status</th>
          </tr>
        </thead> 
        <tbody>
         <% @mm.each do |t|  %> 
            <tr>
                <td><%= t.term_ID %></td> 
               <td><%= t.language_name %></td>
               <td><%= t.term_content %></td>
               <td><%= t.term_organization_name %></td>
                <td><%= t.term_originator_reference %></td>
                <td><% if t.term_is_deprecated== '0' %>
                Active
                <% else %>
                Inactive             
                <% end %> 
            </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>     
  </div>
</div>
<div class="row"> 
  <div class="col-lg-12">
    <div class="ibox" >
      <div class="ibox-title" style="background:#1C84C6;color:#f3f3f4 !important;">
        <h5> <%- if I18n.locale== :ar %>
          <span class="">
            <% @ar_term = Language.select("language_property").where("language_id = ?  AND language_type = ? ", '25','ar')%>
            <% @ar_term.each do |ar_term|%>
            <%= ar_term.language_property %>
             <% end %>
          </span>
        <% else %>
          <span class="">
            <% @en_term = Language.select("language_property").where("language_id = ?  AND language_type = ? ", '25','en')%>
            <% @en_term.each do |en_term|%>
            <%= en_term.language_property %>
             <% end %>
          </span>
        <% end -%> </h5>
        <div class="ibox-tools">
          <a class="collapse-link" style="color:#f3f3f4 !important;">
              <i class="fa fa-chevron-up"></i>
          </a>
         
          <a class="close-link" style="color:#f3f3f4 !important;">
              <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
        <div class="ibox-content" style="border:1px solid #1C84C6;">
          <table class="table table-bordered">
            <thead>
                <tr> 
                    <th>Definition ID</th>
                    <th>Language</th>
                    <th>Term</th>
                    <th>Source</th>
                    <th>Source Reference</th>
                    <th>Status</th>
                </tr>
            </thead> 
            <tbody>
                  <% @mm.each do |d|  %> 
                <tr>
                    <td><%= d.definition_ID %></td> 
                    <td><%= d.language_name %></td>
                    <td><%= d.definition_content %></td>
                    <td><%= d.definition_organization_name %></td>
                    <td><%= d.definition_originator_reference %></td>
                    <td><% if d.definition_is_deprecated== '0' %>
                    Active
                    <% else %>
                    Inactive             
                    <% end %>
                    </td> 
                </tr>
             <% end %>
                </tr>
            </tbody>
          </table>
        </div>
    </div>
  </div>
</div>
<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    var updateOutput = function (e) {
        var list = e.length ? e : $(e.target),
                output = list.data('output');
        if (window.JSON) {
            output.val(window.JSON.stringify(list.nestable('serialize')));
        } else {
            output.val('JSON browser support required for this demo.');
        }
    };
    // activate Nestable for list 1
    $('#nestable').nestable({
        group: 1
    }).on('change', updateOutput);

    // activate Nestable for list 2
    $('#nestable2').nestable({
        group: 1
    }).on('change', updateOutput);

    // output initial serialised data
    updateOutput($('#nestable').data('output', $('#nestable-output')));
    updateOutput($('#nestable2').data('output', $('#nestable2-output')));

    $('#nestable-menu').on('click', function (e) {
        var target = $(e.target),
                action = target.data('action');
        if (action === 'expand-all') {
            $('.dd').nestable('expandAll');
        }
        if (action === 'collapse-all') {
            $('.dd').nestable('collapseAll');
        }
    });

});

</script>

<% end %>
    

app/views/home/index.html.erb
<style>
.ribbon {
  position: absolute;
  right: 13px; top: -5px;
  z-index: 1;
  overflow: hidden;
  width: 75px; height: 75px;
  text-align: right;
}
.ribbon span {
  font-size: 13px;
  font-weight: bold;
  color: #FFF;
  text-align: center;
  line-height: 20px;
  transform: rotate(45deg);
  -webkit-transform: rotate(45deg);
  width: 100px;
  display: block;
  background: #79A70A;
  background: linear-gradient(#9BC90D 0%, #79A70A 100%);
  box-shadow: 0 3px 10px -5px rgba(0, 0, 0, 1);
  position: absolute;
  top: 19px; right: -21px;
}
.ribbon span::before {
  content: "";
  position: absolute; left: 0px; top: 100%;
  z-index: -1;
  border-left: 3px solid #79A70A;
  border-right: 3px solid transparent;
  border-bottom: 3px solid transparent;
  border-top: 3px solid #79A70A;
}
.ribbon span::after {
  content: "";
  position: absolute; right: 0px; top: 100%;
  z-index: -1;
  border-left: 3px solid transparent;
  border-right: 3px solid #79A70A;
  border-bottom: 3px solid transparent;
  border-top: 3px solid #79A70A;
}
</style>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">      
    <div class="clearfix"></div><br><br><br><br>
    <ol class="breadcrumb" style="background:#F3F3F4; padding:6px;">
      <li>
        <%- if I18n.locale== :ar %>
          <span class="">
              <a href="<%= url_for :controller => 'home', :action => 'index' %>">الصفحة الرئيسية</a>                   
          </span>
        <% else %>
          <span class="">
           <a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a>
          </span>
        <% end -%>
        
      </li>
       <li class="active">
          <%- if I18n.locale== :ar %>
          <span class="">eSTS's
              <!-- <a href="<%= url_for :controller => 'home', :action => 'index' %>">eSTS's</a> -->                   
          </span>
        <% else %>
          <span class="">eSTS's
           <!-- <a href="<%= url_for :controller => 'home', :action => 'index' %>">eSTS's</a> -->                   
          </span>
        <% end -%>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <% if flash[:success] %>
        <div class="alert alert-success alert-dismissable">
          <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
          <p><%= flash[:success] %></p>
        </div>
      <% end %> 
      <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissable">
          <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
          <p><%= flash[:alert] %></p>
        </div>
      <% end %> 
      <div class="ibox float-e-margins">                
        <div class="ibox-title" style="background:#1C84C6;color:#f3f3f4 !important;">    
          <h5>
          eSTS's List
          </h5>
        </div>                        
        <div class="ibox-content" style="border:1px solid #1C84C6;">
           <div class="row">
            <div class="col-md-12 col-lg-12 col-xs-12 ">
              <h3 class="pull-left"><span class="text-danger">Total no. of eSTS's available: <%= @madein_count %></span></h3>
              <%= form_tag(home_index_path,:method => "get", class: "navbar-form pull-right") do %>
                <div class="form-group ">                  
                  <div class="pull-right"><%= submit_tag "Search", :class=>"btn btn btn-success", :style=>"margin-left:10px;",:name=>nil %></div>
                  <div class="pull-right"><%= text_field_tag :search, params[:search], class: "span4 form-control", placeholder: "" %></div>
                </div> 
              <% end %>                                 
            </div>
            <div class="col-md-12 col-lg-12 col-xs-12">&nbsp;</div>
             <%for c in @madein_ksa%>
               <div class="col-lg-3 col-md-6 col-xs-12 box">
                  <div class="contact-box center-version" style="height: 250px;overflow: auto;">
                      <a title="Click here to delete" class="pull-left" href="<%= url_for :controller => 'home', :action => 'destroy',:id => c.cat_id %>" onclick="return confirm('Are you sure you want to delete this item?')"><i class="fa fa-trash-o text-danger"></i></a>
                      <a title="Click here to view" href="<%= url_for :controller => 'home', :action => 'view',:cat_id => c.cat_id %>" target="_blank">
                          <% 
                          @image=Image.where("image_id = ?",c.cat_id)
                          @imagecount=Image.where("image_id = ?",c.cat_id).count
                          @cmm=c.cat_id
                          @catid="ECCMA.eTSR:"+@cmm.to_s
                          @etsr_mm=EtsrMaterialMaster.where("cat_id = ?",@catid).count
                          if @imagecount==0 %>
                            <img alt="image" class="img-thumbnail" src="<%= image_url "noimage.jpg" %>"/>
                          <%else%>
                            <%@image.each do |img|%>                  
                             <%= image_tag("ests_images/#{img.image_name}") %>                   
                            <% end %>
                          <% end %>
                           <h4 class="m-b-xs"><strong><span class="text-success"><%=c.short_description.truncate(25) %></span></strong></h4><br>

                          <div class="font-bold">
                            <% 
                              @rxml=RxmlValue.where("cat_id = ? and datedeleted = ? and value!=?",c.cat_id,'0000-00-00 00:00:00','').order(row: :asc).limit(3) 
                              for rxml in @rxml
                              %>
                              <span class="pull-left"><span class=""><%= rxml.property.truncate(20) %></span>:<b><%= rxml.value.truncate(20) %></b></span><br>
                            <% end %>
                        </div>
                      </a>
                      <% if @etsr_mm==1%>
                        <div class="ribbon"><span>eTSR</span></div>
                      <%end%>                        
                  </div>
                </div>
              <% end %>
              <div class="col-md-12"><span class="pull-right"><%= will_paginate @madein_ksa, renderer: BootstrapPagination::Rails  %></span></div>
            </div> 
        </div>
      </div>
    </div>
  </div> 
</div>   