config/routes.rb
Myapp::Application.routes.draw do
  scope "(:locale)", :locale => /en|ar/ do
    devise_scope :user do
      root :to => 'devise/sessions#new'
      delete "sign out" => "devise/session#destroy"
    end
    devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: '', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
    
    get 'home/index' => 'home#index'    
    get 'factory/new' => 'factory#new'
    get 'addnew' => 'home#addnew'
    post 'addnew' => 'home#addnew'
    get 'destroy' => 'home#destroy'
    get 'etsr' => 'home#etsr'
    get 'loadexisting' => 'home#loadexisting'
    post "modalclass" => 'home#modalclass'
    get "modalclass"  => 'home#modalclass'
    post "modalprop" => 'home#modalprop'
    get "modalprop"  => 'home#modalprop'
    get 'settings' => 'setting#index'
    post 'settings' => 'setting#index'
    get 'view' => 'home#view'
    post 'view' => 'home#view'
    post 'update' => 'home#update'
    get 'update' => 'home#update'
    get 'dictionary_detail' => 'home#dictionary_detail'  
    get 'ajax_property' => 'home#ajax_property'  
    get 'template_search' => 'home#template_search'
  end 
end

app/models/concept_dn.rb
require 'safe_attributes/base'
class ConceptDn < ActiveRecord::Base
	self.table_name = 'concept_dn'
end

app/models/corp_igname.rb
require 'safe_attributes/base'
class CorpIgname < ActiveRecord::Base
	include SafeAttributes::Base
end

app/models/countryorigin.rb
class Countryorigin < ActiveRecord::Base
end

app/models/etsr_image.rb
require 'safe_attributes/base'
class Im < ActiveRecord::Base
	self.abstract_class = true
	establish_connection("etsr_#{Rails.env}")
end
class EtsrImage < Im
	include SafeAttributes::Base
	self.table_name = 'images'
end

app/models/etsr_rxml_value.rb
require 'safe_attributes/base'
class Rv < ActiveRecord::Base
	self.abstract_class = true
	establish_connection("etsr_#{Rails.env}")
end
class EtsrRxmlValue < Rv
	include SafeAttributes::Base
	self.table_name = 'rxml_value'
end

app/models/factory.rb
require 'safe_attributes/base'
class Factory < ActiveRecord::Base
	include SafeAttributes::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/organization.rb
require 'safe_attributes/base'
class Organization < ActiveRecord::Base
	include SafeAttributes::Base
	# self.table_name = 'Organization'
end

app/models/orglanguage.rb
require 'safe_attributes/base'
class Orglanguage < ActiveRecord::Base
	include SafeAttributes::Base
	self.table_name = 'language'
end

app/models/rxml_reference.rb
require 'safe_attributes/base'
class RxmlReference < ActiveRecord::Base
	include SafeAttributes::Base
	self.table_name = 'rxml_reference'
end

app/models/rxml_value.rb
require 'safe_attributes/base'
class RxmlValue < ActiveRecord::Base
	include SafeAttributes::Base
	self.table_name = 'rxml_value'
end

app/models/setting.rb
require 'safe_attributes/base'
class Setting < ActiveRecord::Base
	 include SafeAttributes::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
   
  #protected  its is for skip the mail confirmation
  def confirmation_required?
    false
  end
  
  # Validation Purpose
  validates :email, :password, presence: true
  validates :email, uniqueness: true
  
  # Password Complexity
  validate :password_complexity
  def password_complexity
    return unless password.present?
    errors.add :password, "must include at least one lower case letter." unless password =~ /[a-z]/
    errors.add :password, "must include at least one upper case letter."  unless password =~ /[A-Z]/
    errors.add :password, "must include at least one digit." unless password =~ /[\d]/
    errors.add :password, "must include at least one special character." unless password =~ /[\W]/
  end
end

app/models/xml_rg.rb
require 'safe_attributes/base'
class XmlRg < ActiveRecord::Base
	include SafeAttributes::Base
	self.table_name = 'xml_rg'
end

app/models/xml_rg_delete.rb
class XmlRgDelete < ActiveRecord::Base
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
    <div class="alert alert-success alert-dismissable">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
      <h4 class="hide">#{sentence}</h4>
      #{messages}
    </div>
   HTML

   html.html_safe
 end
end

app/helpers/factory_helper.rb
module FactoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        <strong>Email me:</strong>
    	<%= mail_to "info@eccma.org" do %>
	  	 	<span>info@eccma.org</span>
		<% end %>
    </div>
    <div>
        <strong>Copyright</strong> <%= link_to "Eccma", "http://www.eccma.org/", target: '_blank' %> &copy; <%= Time.now.year %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="image" width="100px" class="img-responsive" src="<%= image_url 'eSTS.png' %>"/>
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">                                
                                <% if user_signed_in? %>
                                   <strong class="font-bold"> <%= current_user.Organization_name.upcase %></strong>
                                    </span> 
                                <% end %>
                        </span>
                    </a>
                </div>
                <div class="logo-element">
                    eSTS
                </div>
            </li>
            <li class="<%= 'active' if current_page?('/home/index') %>">
                <%= link_to "/" do %>
                <i class="fa fa-dashboard"></i> <span class="nav-label">Dashboard</span>
                <% end %>
            </li>
            <li class="<%= 'active' if current_page?('/home/addnew') %>">
                <%= link_to "/addnew" do %>
                <i class="fa fa-plus"></i> <span class="nav-label">Add Item</span>
                <% end %>
            </li>
            <li class="<% if controller.controller_name == "registrations" && controller.action_name == "edit" %>active<%end%>">
                 <%- if I18n.locale== :ar %>
                    <%= link_to '<i class="fa fa-user"></i> <span class="nav-label">تعديل الملف الشخصي</span>'.html_safe,  edit_user_registration_path %> 
                  <% else %>
                    <%= link_to '<i class="fa fa-user"></i> <span class="nav-label">Edit Profile</span>'.html_safe,  edit_user_registration_path %> 
                <% end -%> 
            </li>
            <li class="<% if controller.controller_name == "setting" && controller.action_name == "index" %>active<%end%>">
                <%- if I18n.locale== :ar %> 
                    <%= link_to '<i class="fa fa-cog"></i> <span class="nav-label">إعدادات</span>'.html_safe, settings_path %>
                <% else %>     
                    <%= link_to '<i class="fa fa-cog"></i> <span class="nav-label">Settings</span>'.html_safe, settings_path %>
                <% end -%> 
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
     <nav class="navbar navbar-fixed-top" role="navigation">  
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href="#"><i class="fa fa-bars"></i> </a>  
            <h3 style="color:white;" class="pull-left">
                 <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 <%- if I18n.locale== :ar %>
                   eSTS-ECCMA Standard Technical Specification
                  <% else %>
                    eSTS-ECCMA Standard Technical Specification
                <% end -%> 
            </h3>          
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li class="hide"><span style="color:white">English</span></li>
            <li>
                <%- if I18n.locale== :ar %>
                   <%= link_to ' تسجيل خروج <i class="fa fa-sign-out"></i>'.html_safe,  destroy_user_session_path, method: :delete  %>
                  <% else %>
                    <%= link_to ' Logout <i class="fa fa-sign-out"></i>'.html_safe,  destroy_user_session_path, method: :delete  %>
                <% end -%>                 
            </li>                      
        </ul>
    </nav>
</div>

app/views/layouts/_topnavbar_2.html.erb
<style>
#navbar{
    margin-bottom: 0;
    background-image: url("<%= image_url 'banner.jpg' %>") !important;
    background-repeat:no-repeat;
    background-position:center;
    color: white;
}
/* this one goes for default images - bigger sizes */
@media all and (min-width: 1024px) {
    #navbar {
        background-image: url("<%= image_url 'banner.jpg' %>") !important; /*in the case you have another image for this resolution*/
        background-size: 1940px auto;
    }
}
/* for default - too short - size */
@media all and (max-width: 319px) {
    #navbar {
        background-image: url('my-image-very-small.png'); /*in the case you have another image for this resolution - usually you'll never have these sizes as for today*/
        background-size: 200px 150px;
    }
}

@media all and (max-width: 639px) and (min-width: 320px) {
    #navbar {
        background-image: url("<%= image_url 'banner.jpg' %>") !important; /*in the case you have another image for this resolution*/
        background-size: 320px 240px;
    }
}

@media all and (max-width: 799px) and (min-width: 640px) {
    #navbar {
        background-image: url('<%= image_url 'banner.jpg' %>'); /*in the case you have another image for this resolution*/
        background-size: 640px 480px;
    }
}

@media all and (max-width: 1023px) and (min-width: 800px) {
    #navbar {
        background-image: url("<%= image_url 'banner.jpg' %>") !important; /*in the case you have another image for this resolution*/
        background-size: 800px 600px;
    }
}

/* this will have no @media, so will apply for every resolution */
#navbar {
    background-repeat:no-repeat;
    background-position:center;
    width: 100%; /* assuming you want to expand your div in a screen-dependent way */
}

#navbar .nav > li > a {
    padding: 15px 20px;
    color: white;
}
#navbar .nav > li > a:hover {
    padding: 15px 20px;
    background-color: #3774A8;
    color: white;
}
#navbar .nav > li.active{
   /*border-radius: 5px;*/
   background-color: #3774A8 !important;
   color: #1C84C6;
}
.wrapper.wrapper-content {
    padding: 20px 40px !important;
}
.breadcrumb > li a {
    color: #1C84C6 !important;
}
</style>
<div class="row border-bottom">
    <nav class="navbar navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <i class="fa fa-reorder"></i>
        </button>
         <span>
            <img alt="image" class="img-responsive" src="<%= image_url 'eSTS.png' %>" style="padding: 10px;padding-left: 40px;"/>
        </span>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
        <ul class="nav navbar-nav" style="padding-left: 30px;">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><h3 style="padding-left: 19px; color: ;">eSTS-ECCMA Standard Technical Specification</h3></strong>
            <li class="<% if controller.controller_name == "home" && controller.action_name == "index" %>active<%end%>">
                <%= link_to "/" do %>
                <i class="fa fa-dashboard"></i> <span class="nav-label">eSTS's</span>
                <% end %>
            </li>
            <li class="<% if controller.controller_name == "home" && controller.action_name == "addnew" %>active<%end%>">
                <%= link_to "/addnew" do %>
                <i class="fa fa-plus"></i> <span class="nav-label">Add Item</span>
                <% end %>
            </li>
            <li class="<% if controller.controller_name == "registrations" && controller.action_name == "edit" %>active<%end%> hide">
                 <%- if I18n.locale== :ar %>
                    <%= link_to '<i class="fa fa-user"></i> <span class="nav-label">تعديل الملف الشخصي</span>'.html_safe,  edit_user_registration_path %> 
                  <% else %>
                    <%= link_to '<i class="fa fa-user"></i> <span class="nav-label">Edit Profile</span>'.html_safe,  edit_user_registration_path %> 
                <% end -%> 
            </li>
            <li class="<% if controller.controller_name == "home" && controller.action_name == "template_search" %>active<%end%> hide">
                <%- if I18n.locale== :ar %>
                    <%= link_to '<i class="fa fa-search"></i> <span class="nav-label">قالب البحث</span>'.html_safe, template_search_path %> 
                <% else %>    
                    <%= link_to '<i class="fa fa-search"></i> <span class="nav-label">Search Template</span>'.html_safe, template_search_path %> 
                <% end -%>
            </li>
            <li>
               <a href="http://eccma.org/etsr_ests" target="_blank"><i class="fa fa-search"></i> <span class="nav-label">View eTSR</span></a> 
            </li>
            <li class="<% if controller.controller_name == "setting" && controller.action_name == "index" %>active<%end%>">
                <%- if I18n.locale== :ar %> 
                    <%= link_to '<i class="fa fa-cog"></i> <span class="nav-label">إعدادات</span>'.html_safe, settings_path %>
                <% else %>     
                    <%= link_to '<i class="fa fa-cog"></i> <span class="nav-label">Settings</span>'.html_safe, settings_path %>
                <% end -%> 
            </li>
        </ul>
        <ul class="nav navbar-top-links navbar-right" style="padding-top: 30px;padding-left: 30px;">
            <li>
                <% if user_signed_in? %>
                   <strong class="font-bold"><i class="fa fa-user"></i> <%= current_user.Organization_name.upcase %></strong>
                    </span>
                <% end %>
            </li>
            <li>
                <%- if I18n.locale== :ar %>
                   <%= link_to ' تسجيل خروج <i class="fa fa-sign-out"></i>'.html_safe,  destroy_user_session_path, method: :delete  %>
                  <% else %>
                    <%= link_to ' Logout <i class="fa fa-sign-out"></i>'.html_safe,  destroy_user_session_path, method: :delete  %>
                <% end -%>
                 
            </li>
        </ul>
    </div>
</nav>
<br>
<br>
<br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>eSTS</title>
    <!-- Include style per-controller - vendor plugins -->
    <%#= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css.scss") %>
    <!-- Main css styles -->
    <%- if I18n.locale== :ar %>
        <%= stylesheet_link_tag    'applicationrtls', media: 'all', 'data-turbolinks-track' => true %>
        <% else %>
        <!-- Main javascript files -->
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <% end -%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <style>
    .borderlesstext {
            border: 0;
            background:transparent;
        }
    .borderless {
            border-bottom:0px !important;
        }
        .borderless th, .borderless td {
            border: 0px !important;
        }
        .borderless {
            border:0px !important;
        }
        .custom-tab .nav-tabs > li.active > a, .tabs-container .nav-tabs > li.active > a:hover, .tabs-container .nav-tabs > li.active > a:focus{
            background-color: #1C84C6;
            color: white;
        }        
        .check{
            background-image: url("<%= image_url 'login1.jpg' %>") !important;
        }
        .btn-circle {
            width: 20px;
            height: 20px;
            padding: 3px 0;
            border-radius: 15px;
            text-align: center;
            font-size: 12px;
            line-height: 0.42857;
        }
    </style>
</head>
<%- if I18n.locale== :ar %>
    <body class="pace-done top-navigation rtls boxed-layout">
    <% else %>
    <body class="pace-done top-navigation boxed-layout" >
<% end -%>
    <div id="wrapper wrapper-content" class="white-bg check" id="check">
        <% if user_signed_in? %>
            <!-- Navigation -->
            <%#= render 'layouts/navigation' %>
            <!-- Page wraper -->
            <div id="page-wrapper" class="gray-bg">
                <!-- Page wrapper -->
                <%= render 'layouts/topnavbar_2' %>
                <!-- Main view  -->
                <%= yield %>
                <!-- Footer -->
                <%= render 'layouts/footer' %>
            </div>
            <!-- End page wrapper-->
        <% else %>
            <%= yield %>
            </br>
            <div class="col-md-4"></div>
            <div class="col-md-4 hide">
            <%- if I18n.locale== :ar %>
                <p style="text-align:center;"><%= link_to_unless I18n.locale == :en, "English", locale: :en %> | العربية</p>
            <% else %>  
                <p style="text-align:center;"> English | <%= link_to_unless I18n.locale == :de, "العربية", locale: :ar %></p>
            <% end -%></div>
            <div class="col-md-4"></div>
        <% end %>   
    </div>
    <!-- End wrapper-->
    <%#= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js.coffee") %>
    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>
</body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>eSTS</title>
    <%- if I18n.locale== :ar %>
        <%= stylesheet_link_tag    'applicationrtls', media: 'all', 'data-turbolinks-track' => true %>
        <% else %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <% end -%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <style>
    .borderlesstext {
            border: 0;
            background:transparent;
        }
    .borderless {
            border-bottom:0px !important;
        }
        .borderless th, .borderless td {
            border: 0px !important;
        }
        .borderless {
            border:0px !important;
        }
        .custom-tab .nav-tabs > li.active > a, .tabs-container .nav-tabs > li.active > a:hover, .tabs-container .nav-tabs > li.active > a:focus{
            background-color: #009688;
        }
    </style>
</head>
<%- if I18n.locale== :ar %>
    <body class="md-skin fixed-nav rtls">
    <% else %>
    <body class="md-skin fixed-nav ">
<% end -%>
    <div id="wrapper">
        <% if user_signed_in? %>
            <%= render 'layouts/navigation' %>
            <div id="page-wrapper" class="gray-bg">
                <%= render 'layouts/topnavbar' %>                  
                <%= yield %>
                <%= render 'layouts/footer' %>
            </div>
        <% else %>
            <%= yield %>
            </br>
            <div class="col-md-4"></div>
            <div class="col-md-4 hide">
            <%- if I18n.locale== :ar %>
                <p style="text-align:center;"><%= link_to_unless I18n.locale == :en, "English", locale: :en %> | العربية</p>
            <% else %>  
                <p style="text-align:center;"> English | <%= link_to_unless I18n.locale == :de, "العربية", locale: :ar %></p>
            <% end -%></div>
            <div class="col-md-4"></div>
        <% end %>   
    </div>
    <%= yield :javascript %>
</body>
</html>

app/views/layouts/layout_2.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>INSPINIA | Responsive admin theme</title>
    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>
    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>



</head>
<body class="top-navigation">
    <!-- Wrapper-->
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">
        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg <%= @extra_class %>">
            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar_2' %>
            <!-- Main view  -->
            <%= yield %>
            <!-- Footer -->
            <%= render 'layouts/footer' %>
        </div>
        <!-- End page wrapper-->
    </div>
    <!-- End wrapper-->
    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>
</body>
</html>